apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cktn6ly5b-go 
  janus-idp.io/tekton: cktn6ly5b-go
  backstage.io/kubernetes-id: cktn6ly5b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cktn6ly5b-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml